### PR TITLE
Create an NFT marketplace on sui

### PR DESCRIPTION
**Pull request by kushagara175**
full steps on ow to create nft marketplace on sui

### CODE REVIEW

**Review by kushagara175 — COMMENTED** [review]
Create NFT marketplace on sui

**Comment by hyd628** [comment]
Not what this repo is for.

**Comment by kushagara175** [comment]
> Not what this repo is for.

ok brother

**Comment by kushagara175** [comment]
> Not what this repo is for.

so please tell me bro in which repo i can post that

**Pull request closed without merging**
